import '../../models/item_model.dart';

class LocalInventoryDataSource {
  static final LocalInventoryDataSource _instance =
      LocalInventoryDataSource._internal();

  factory LocalInventoryDataSource() => _instance;

  LocalInventoryDataSource._internal();

  final List<Item> items = [
    Item(
      id: 1,
      name: 'On the Fall of an Aeon',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A legendary Light Cone associated with overwhelming destructive force. Its fragmented memory echoes the collapse of civilizations consumed by unstoppable power. Often synchronized with warriors who continue advancing despite catastrophic odds.',
      stock: 4,
      price: 920,
      emoji: '🌌',
      imagePath: 'assets/images/lc_1_on_the_fall_of_an_aeon.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 2,
      name: 'Something Irreplaceable',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A Light Cone carrying the lingering warmth of companionship and sacrifice. Its combat synchronization enhances resilience during extended battles while preserving the emotional memory of someone impossible to replace.',
      stock: 5,
      price: 880,
      emoji: '🛡️',
      imagePath: 'assets/images/lc_2_something_irreplaceable.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 3,
      name: 'The Unreachable Side',
      type: 'lightcone',
      label: 'LC',
      desc:
          'This Light Cone manifests the isolation of warriors who stand beyond ordinary understanding. The encoded combat records amplify offensive synchronization while suppressing hesitation during critical encounters.',
      stock: 3,
      price: 910,
      emoji: '⚔️',
      imagePath: 'assets/images/lc_3_the_unreachable_side.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 4,
      name: 'Brighter Than the Sun',
      type: 'lightcone',
      label: 'LC',
      desc:
          'An advanced combat Light Cone overflowing with draconic energy signatures. Its blazing synchronization pattern dramatically boosts offensive potential and reflects the radiance of a warrior burning brighter than celestial bodies.',
      stock: 5,
      price: 980,
      emoji: '☀️',
      imagePath: 'assets/images/lc_4_brighter_than_the_sun.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 5,
      name: 'A Secret Vow',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A covertly encrypted Light Cone linked to silent determination and hidden promises. Its combat resonance intensifies when confronting stronger enemies, rewarding operators who fight despite impossible circumstances.',
      stock: 7,
      price: 520,
      emoji: '🗡️',
      imagePath: 'assets/images/lc_5_a_secret_vow.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 6,
      name: 'Under the Blue Sky',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A combat-oriented Light Cone preserving fleeting memories of peace beneath endless skies. Despite its calm appearance, the synchronization records reveal explosive bursts of destructive capability during combat.',
      stock: 8,
      price: 450,
      emoji: '🌤️',
      imagePath: 'assets/images/lc_6_under_the_blue_sky.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 7,
      name: 'Nowhere to Run',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A relentless pursuit-oriented Light Cone utilized by aggressive frontline operatives. It continuously reinforces combat pressure while sustaining the user through prolonged close-range engagements.',
      stock: 6,
      price: 510,
      emoji: '🏃',
      imagePath: 'assets/images/lc_7_nowhere_to_run.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 8,
      name: 'Cruising in the Stellar Sea',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A Light Cone developed for high-precision stellar expeditions. Its synchronization algorithm improves critical combat calculations while adapting efficiently to extended deep-space encounters.',
      stock: 4,
      price: 890,
      emoji: '🚀',
      imagePath: 'assets/images/lc_8_cruising_in_the_stellar_sea.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 9,
      name: 'In the Night',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A stealth-oriented Light Cone optimized for high-speed assassination maneuvers. The encoded combat patterns drastically improve precision and movement efficiency under extreme battlefield pressure.',
      stock: 3,
      price: 970,
      emoji: '🌙',
      imagePath: 'assets/images/lc_9_in_the_night.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 10,
      name: 'Sleep Like the Dead',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A sniper-class Light Cone preserving combat memories of silent executions. It recalibrates targeting systems after failed critical strikes, ensuring repeated offensive opportunities during combat.',
      stock: 4,
      price: 860,
      emoji: '💀',
      imagePath: 'assets/images/lc_10_sleep_like_the_dead.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 11,
      name: 'Worrisome, Blissful',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A strangely elegant Light Cone balancing emotional instability with deadly efficiency. The encoded resonance amplifies pursuit capabilities while inducing overwhelming combat fixation.',
      stock: 5,
      price: 780,
      emoji: '🩸',
      imagePath: 'assets/images/lc_11_worrisome_blissful.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 12,
      name: 'Swordplay',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A rapid-strike combat Light Cone engineered around relentless offensive repetition. Consecutive attacks progressively strengthen synchronization output during extended engagements.',
      stock: 8,
      price: 430,
      emoji: '⚔️',
      imagePath: 'assets/images/lc_12_swordplay.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 13,
      name: 'Only Silence Remains',
      type: 'lightcone',
      label: 'LC',
      desc:
          'This Light Cone archives the chilling stillness following successful elimination operations. It enhances critical targeting systems when enemy presence is limited.',
      stock: 7,
      price: 440,
      emoji: '🎯',
      imagePath: 'assets/images/lc_13_only_silence_remains.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 14,
      name: 'River Flows in Spring',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A graceful Light Cone preserving memories of peaceful journeys through recovering worlds. Its synchronization pattern rewards uninterrupted movement and sustained combat rhythm.',
      stock: 6,
      price: 400,
      emoji: '🌊',
      imagePath: 'assets/images/lc_14_river_flows_in_spring.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 15,
      name: 'Before Dawn',
      type: 'lightcone',
      label: 'LC',
      desc:
          'An elite Light Cone infused with devastating intellectual combat algorithms. It significantly amplifies follow-up attack systems and advanced tactical calculations.',
      stock: 2,
      price: 1000,
      emoji: '🌌',
      imagePath: 'assets/images/lc_15_before_dawn.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 16,
      name: 'Night on the Milky Way',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A legendary Light Cone created from records of interstellar exploration. Its synchronization becomes increasingly powerful against overwhelming enemy formations.',
      stock: 3,
      price: 980,
      emoji: '✨',
      imagePath: 'assets/images/lc_16_night_on_the_milky_way.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 17,
      name: 'An Instant Before A Gaze',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A memory-focused Light Cone preserving fleeting moments before irreversible decisions. The resonance output dramatically strengthens ultimate combat synchronization.',
      stock: 5,
      price: 730,
      emoji: '👁️',
      imagePath: 'assets/images/lc_17_an_instant_before_a_gaze.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 18,
      name: 'Today Is Another Peaceful Day',
      type: 'lightcone',
      label: 'LC',
      desc:
          'Despite its comforting title, this Light Cone contains extensive combat adaptation records. Its synchronization efficiency scales proportionally with accumulated operational energy.',
      stock: 6,
      price: 520,
      emoji: '☕',
      imagePath: 'assets/images/lc_18_today_is_another_peaceful_day.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 19,
      name: 'The Birth of the Self',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A sophisticated Light Cone specializing in autonomous combat systems and independent strike calculations. Frequently associated with mechanical entities and follow-up attack synchronization.',
      stock: 5,
      price: 540,
      emoji: '🤖',
      imagePath: 'assets/images/lc_19_the_birth_of_the_self.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 20,
      name: 'The Seriousness of Breakfast',
      type: 'lightcone',
      label: 'LC',
      desc:
          'An oddly practical Light Cone proving that routine preparation can coexist with overwhelming firepower. Offensive synchronization continuously improves after enemy elimination.',
      stock: 9,
      price: 390,
      emoji: '🍳',
      imagePath: 'assets/images/lc_20_the_seriousness_of_breakfast.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 21,
      name: 'Geniuses’ Repose',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A tactical Light Cone preserving combat theories developed by extraordinary intellects. Critical combat output rises dramatically following successful enemy suppression.',
      stock: 4,
      price: 610,
      emoji: '🧠',
      imagePath: 'assets/images/lc_21_geniuses_repose.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 22,
      name: 'But the Battle Isn’t Over',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A prestigious command-oriented Light Cone designed for prolonged tactical engagements. It restores operational efficiency while empowering allied synchronization protocols.',
      stock: 2,
      price: 980,
      emoji: '🎼',
      imagePath: 'assets/images/lc_22_but_the_battle_isnt_over.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 23,
      name: 'Past Self in Mirror',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A reflective Light Cone preserving fragmented identities from alternate possibilities. It amplifies harmony synchronization while stabilizing advanced energy resonance.',
      stock: 3,
      price: 930,
      emoji: '🪞',
      imagePath: 'assets/images/lc_23_past_self_in_mirror.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 24,
      name: 'Dance! Dance! Dance!',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A rhythm-based support Light Cone frequently associated with celebrations aboard the Astral Express. Its synchronization pattern accelerates allied combat movement after ultimate activation.',
      stock: 7,
      price: 480,
      emoji: '💃',
      imagePath: 'assets/images/lc_24_dance_dance_dance.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 25,
      name: 'Memories of the Past',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A melancholic Light Cone carrying the fading resonance of forgotten eras. Its synchronization gradually restores energy while preserving traces of ancient harmony.',
      stock: 6,
      price: 510,
      emoji: '📖',
      imagePath: 'assets/images/lc_25_memories_of_the_past.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 26,
      name: 'Planetary Rendezvous',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A diplomatic Light Cone documenting peaceful encounters across distant worlds. It strengthens allies sharing synchronized elemental resonance patterns.',
      stock: 6,
      price: 470,
      emoji: '🪐',
      imagePath: 'assets/images/lc_26_planetary_rendezvous.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 27,
      name: 'Carve the Moon, Weave the Clouds',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A ceremonial Light Cone inspired by elegant artistic traditions. Its shifting synchronization patterns continuously rotate through multiple combat enhancements.',
      stock: 4,
      price: 680,
      emoji: '☁️',
      imagePath: 'assets/images/lc_27_carve_the_moon_weave_the_clouds.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 28,
      name: 'Meshing Cogs',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A compact mechanical Light Cone utilizing repetitive energy cycling systems. Despite its simple appearance, it remains highly efficient for rapid energy restoration.',
      stock: 12,
      price: 220,
      emoji: '⚙️',
      imagePath: 'assets/images/lc_28_meshing_cogs.png',
      rarity: '3-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 29,
      name: 'In the Name of the World',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A powerful Nihility-class Light Cone infused with oppressive psychological pressure. Enemy targets suffer intensified debilitation under its synchronization field.',
      stock: 3,
      price: 960,
      emoji: '🌍',
      imagePath: 'assets/images/lc_29_in_the_name_of_the_world.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 30,
      name: 'Patience Is All You Need',
      type: 'lightcone',
      label: 'LC',
      desc:
          'Kafka’s signature Light Cone designed around inevitability and gradual collapse. It inflicts accumulating pressure through repeated offensive synchronization and devastating follow-up resonance.',
      stock: 2,
      price: 1100,
      emoji: '🕸️',
      imagePath: 'assets/images/lc_30_patience_is_all_you_need.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 31,
      name: 'Resolution Shines as Pearls of Sweat',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A covert tactical Light Cone specialized in weakening enemy defenses through calculated pressure and continuous pursuit synchronization.',
      stock: 5,
      price: 570,
      emoji: '💧',
      imagePath: 'assets/images/lc_31_resolution_shines_as_pearls_of_sweat.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 32,
      name: 'Good Night and Sleep Well',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A sinister Nihility Light Cone that grows stronger as enemy targets accumulate debuffs. Its encoded resonance reflects exhaustion, manipulation, and inevitable collapse.',
      stock: 6,
      price: 620,
      emoji: '🌃',
      imagePath: 'assets/images/lc_32_good_night_and_sleep_well.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 33,
      name: 'Eyes of the Prey',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A predatory Light Cone developed for relentless debuff application and target tracking. It enhances effect hit rate while intensifying damage-over-time synchronization.',
      stock: 5,
      price: 610,
      emoji: '👁️',
      imagePath: 'assets/images/lc_33_eyes_of_the_prey.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 34,
      name: 'Fermata',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A rhythmically unstable Light Cone associated with electrical disruption and sustained damage resonance. Particularly effective alongside shock-oriented operators.',
      stock: 7,
      price: 430,
      emoji: '🎵',
      imagePath: 'assets/images/lc_34_fermata.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 35,
      name: 'Trend of the Universal Market',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A commercially themed preservation Light Cone documenting the chaotic fluctuations of interstellar economies. Defensive synchronization occasionally redirects enemy aggression.',
      stock: 8,
      price: 450,
      emoji: '📈',
      imagePath: 'assets/images/lc_35_trend_of_the_universal_market.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 36,
      name: 'Subscribe for More!',
      type: 'lightcone',
      label: 'LC',
      desc:
          'An aggressively energetic Light Cone designed around audience engagement and explosive performance output. Ultimate synchronization receives significant amplification.',
      stock: 6,
      price: 490,
      emoji: '📺',
      imagePath: 'assets/images/lc_36_subscribe_for_more.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 37,
      name: 'Make the World Clamor',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A chaotic entertainment-oriented Light Cone overflowing with noise and unstable energy patterns. It rapidly accelerates ultimate activation readiness.',
      stock: 6,
      price: 500,
      emoji: '📢',
      imagePath: 'assets/images/lc_37_make_the_world_clamor.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 38,
      name: 'Return to Darkness',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A hunt-class Light Cone emphasizing precision elimination and tactical suppression. Critical synchronization may erase enemy enhancements during combat.',
      stock: 5,
      price: 620,
      emoji: '🌑',
      imagePath: 'assets/images/lc_38_return_to_darkness.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 39,
      name: 'The Moles Welcome You',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A playful yet surprisingly effective combat Light Cone developed around adaptive attack combinations and layered synchronization bonuses.',
      stock: 8,
      price: 390,
      emoji: '🐹',
      imagePath: 'assets/images/lc_39_the_moles_welcome_you.png',
      rarity: '4-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 40,
      name: 'Geniuses’ Greetings',
      type: 'lightcone',
      label: 'LC',
      desc:
          'A highly experimental Light Cone associated with intellectual collaboration and unstable research synchronization. Its encoded data reflects curiosity bordering on dangerous obsession.',
      stock: 4,
      price: 760,
      emoji: '🧪',
      imagePath: 'assets/images/lc_40_geniuses_greetings.png',
      rarity: '5-star',
      category: 'LIGHT CONE',
      eventTag: null,
    ),
    Item(
      id: 41,
      name: 'Credits',
      type: 'resource',
      label: 'RES',
      desc:
          'The universal currency circulating across countless worlds connected by the Interastral Peace Corporation. Although ordinary in appearance, Credits remain the foundation of all trade, logistics, and expeditionary operations throughout the galaxy.',
      stock: 999,
      price: 12,
      emoji: '💳',
      imagePath: 'assets/images/res_1_credits.png',
      rarity: '3-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 42,
      name: 'Stellar Jade',
      type: 'resource',
      label: 'RES',
      desc:
          'A rare crystalline material carrying condensed stellar energy. Frequently exchanged for high-level warp synchronization access and regarded as one of the most valuable strategic resources among Trailblazers.',
      stock: 120,
      price: 180,
      emoji: '💎',
      imagePath: 'assets/images/res_2_stellar_jade.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 43,
      name: 'Undying Starlight',
      type: 'resource',
      label: 'RES',
      desc:
          'A radiant fragment left behind after advanced warp synchronization procedures. The energy within remains remarkably stable and is often exchanged for premium archival equipment.',
      stock: 88,
      price: 130,
      emoji: '✨',
      imagePath: 'assets/images/res_3_undying_starlight.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 44,
      name: 'Undying Embers',
      type: 'resource',
      label: 'RES',
      desc:
          'Residual energy particles recovered after large-scale warp operations. Though less refined than Starlight, these embers retain enough value to support routine supply exchanges.',
      stock: 210,
      price: 72,
      emoji: '🔥',
      imagePath: 'assets/images/res_4_undying_embers.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 45,
      name: 'Herta Bond',
      type: 'resource',
      label: 'RES',
      desc:
          'A specialized exchange token issued by Herta Space Station. These bonds are distributed to operatives who survive high-risk Simulated Universe operations and maintain synchronization stability.',
      stock: 40,
      price: 260,
      emoji: '🛰️',
      imagePath: 'assets/images/res_5_herta_bond.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 46,
      name: 'Oneiric Shard',
      type: 'resource',
      label: 'RES',
      desc:
          'An artificial dream-derived crystal refined through advanced commercial processing. Its energy structure is highly compatible with premium warp acquisition systems.',
      stock: 60,
      price: 240,
      emoji: '🪞',
      imagePath: 'assets/images/res_6_oneiric_shard.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 47,
      name: 'Travel Encounters',
      type: 'resource',
      label: 'RES',
      desc:
          'A collection of introductory expeditionary logs compiled for inexperienced Trailblazers. The material contains basic tactical records gathered during early interstellar journeys.',
      stock: 180,
      price: 28,
      emoji: '📘',
      imagePath: 'assets/images/res_7_travel_encounters.png',
      rarity: '3-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 48,
      name: 'Adventure Log',
      type: 'resource',
      label: 'RES',
      desc:
          'A standardized archive containing practical field reports from experienced operatives. Frequently utilized to accelerate combat adaptation and operational growth.',
      stock: 145,
      price: 52,
      emoji: '📚',
      imagePath: 'assets/images/res_8_adventure_log.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 49,
      name: 'Traveler’s Guide',
      type: 'resource',
      label: 'RES',
      desc:
          'An advanced training archive prepared for elite interstellar expeditions. Its dense combat records dramatically improve synchronization efficiency during operator development.',
      stock: 90,
      price: 96,
      emoji: '🗺️',
      imagePath: 'assets/images/res_9_travelers_guide.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 50,
      name: 'Sparse Aether',
      type: 'resource',
      label: 'RES',
      desc:
          'A diluted energy fragment extracted from unstable stellar residue. Although weak individually, Sparse Aether remains essential for routine Light Cone calibration procedures.',
      stock: 220,
      price: 24,
      emoji: '🧬',
      imagePath: 'assets/images/res_10_sparse_aether.png',
      rarity: '3-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 51,
      name: 'Condensed Aether',
      type: 'resource',
      label: 'RES',
      desc:
          'A stabilized form of concentrated stellar energy refined through advanced compression methods. Commonly used to strengthen synchronization pathways inside Light Cones.',
      stock: 170,
      price: 48,
      emoji: '⚡',
      imagePath: 'assets/images/res_11_condensed_aether.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 52,
      name: 'Refined Aether',
      type: 'resource',
      label: 'RES',
      desc:
          'A highly purified stellar energy catalyst reserved for premium synchronization enhancement. The refinement process dramatically increases compatibility with advanced Light Cones.',
      stock: 82,
      price: 94,
      emoji: '🌠',
      imagePath: 'assets/images/res_12_refined_aether.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 53,
      name: 'Arrow of the Beast Hunter',
      type: 'resource',
      label: 'RES',
      desc:
          'A combat ascension material associated with relentless hunting expeditions across hostile territories. The embedded resonance improves offensive synchronization against dangerous targets.',
      stock: 90,
      price: 56,
      emoji: '🏹',
      imagePath: 'assets/images/res_13_arrow_of_the_beast_hunter.png',
      rarity: '3-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 54,
      name: 'Arrow of the Demon Slayer',
      type: 'resource',
      label: 'RES',
      desc:
          'A sharpened ascension catalyst forged from records of violent extermination campaigns. Its destructive resonance significantly enhances offensive combat pathways.',
      stock: 74,
      price: 84,
      emoji: '🗡️',
      imagePath: 'assets/images/res_14_arrow_of_the_demon_slayer.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 55,
      name: 'Arrow of the Starchaser',
      type: 'resource',
      label: 'RES',
      desc:
          'A refined stellar projectile core associated with elite pursuit specialists. The material resonates strongly with high-speed precision synchronization systems.',
      stock: 55,
      price: 122,
      emoji: '🌌',
      imagePath: 'assets/images/res_15_arrow_of_the_starchaser.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 56,
      name: 'Key of Inspiration',
      type: 'resource',
      label: 'RES',
      desc:
          'An encrypted memory catalyst used to unlock basic cognitive synchronization pathways. Widely distributed throughout educational and tactical institutions.',
      stock: 180,
      price: 34,
      emoji: '🗝️',
      imagePath: 'assets/images/res_16_key_of_inspiration.png',
      rarity: '3-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 57,
      name: 'Key of Knowledge',
      type: 'resource',
      label: 'RES',
      desc:
          'A refined cognitive archive fragment capable of accelerating advanced operational understanding. Often utilized during high-level tactical synchronization.',
      stock: 120,
      price: 64,
      emoji: '📖',
      imagePath: 'assets/images/res_17_key_of_knowledge.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 58,
      name: 'Key of Wisdom',
      type: 'resource',
      label: 'RES',
      desc:
          'An exceptionally valuable cognitive resonance core reserved for elite synchronization development. The internal data structure remains remarkably stable under heavy processing.',
      stock: 65,
      price: 108,
      emoji: '🧠',
      imagePath: 'assets/images/res_18_key_of_wisdom.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 59,
      name: 'Obsidian of Dread',
      type: 'resource',
      label: 'RES',
      desc:
          'A dark crystallized fragment saturated with oppressive resonance. Frequently associated with Nihility-aligned operators and psychologically destabilizing synchronization fields.',
      stock: 88,
      price: 72,
      emoji: '🖤',
      imagePath: 'assets/images/res_19_obsidian_of_dread.png',
      rarity: '3-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 60,
      name: 'Obsidian of Desolation',
      type: 'resource',
      label: 'RES',
      desc:
          'A refined obsidian catalyst carrying traces of catastrophic emotional resonance. Its synchronization signature intensifies sustained damage-over-time effects.',
      stock: 62,
      price: 104,
      emoji: '🌑',
      imagePath: 'assets/images/res_20_obsidian_of_desolation.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 61,
      name: 'Obsidian of Obsession',
      type: 'resource',
      label: 'RES',
      desc:
          'An advanced obsidian catalyst infused with dangerously concentrated emotional resonance. Operators synchronized with this material often display relentless fixation and overwhelming combat persistence.',
      stock: 44,
      price: 148,
      emoji: '🕷️',
      imagePath: 'assets/images/res_21_obsidian_of_obsession.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 62,
      name: 'Harmonic Tune',
      type: 'resource',
      label: 'RES',
      desc:
          'A delicate resonance fragment extracted from stabilized harmonic frequencies. Commonly used during support-class synchronization procedures and musical combat calibration.',
      stock: 130,
      price: 42,
      emoji: '🎵',
      imagePath: 'assets/images/res_22_harmonic_tune.png',
      rarity: '3-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 63,
      name: 'Ancestral Hymn',
      type: 'resource',
      label: 'RES',
      desc:
          'An ancient ceremonial resonance archive preserving echoes of forgotten civilizations. Its synchronization properties strengthen support-oriented combat pathways.',
      stock: 88,
      price: 76,
      emoji: '🎼',
      imagePath: 'assets/images/res_23_ancestral_hymn.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 64,
      name: 'Stellaris Symphony',
      type: 'resource',
      label: 'RES',
      desc:
          'A grand orchestral resonance core composed of layered stellar frequencies. This rare material dramatically improves harmony synchronization during high-level operations.',
      stock: 46,
      price: 134,
      emoji: '🌌',
      imagePath: 'assets/images/res_24_stellaris_symphony.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 65,
      name: 'Oath of Steel',
      type: 'resource',
      label: 'RES',
      desc:
          'A reinforced combat ascension material forged from heavily compressed metallic resonance. Frequently utilized by frontline operatives specializing in direct confrontation.',
      stock: 110,
      price: 54,
      emoji: '🛡️',
      imagePath: 'assets/images/res_25_oath_of_steel.png',
      rarity: '3-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 66,
      name: 'Safeguard of Amber',
      type: 'resource',
      label: 'RES',
      desc:
          'A preservation-oriented defensive catalyst designed to stabilize synchronization barriers under sustained enemy pressure. Widely employed in high-risk expeditionary missions.',
      stock: 84,
      price: 86,
      emoji: '🟠',
      imagePath: 'assets/images/res_26_safeguard_of_amber.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 67,
      name: 'Seed of Abundance',
      type: 'resource',
      label: 'RES',
      desc:
          'A biologically active resonance seed associated with regenerative synchronization pathways. The internal energy structure promotes accelerated recovery efficiency.',
      stock: 76,
      price: 94,
      emoji: '🌱',
      imagePath: 'assets/images/res_27_seed_of_abundance.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 68,
      name: 'Sprout of Life',
      type: 'resource',
      label: 'RES',
      desc:
          'A vibrant growth catalyst preserving traces of regenerative stellar energy. Commonly integrated into healing-class synchronization systems and recovery protocols.',
      stock: 66,
      price: 118,
      emoji: '🌿',
      imagePath: 'assets/images/res_28_sprout_of_life.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 69,
      name: 'Flower of Eternity',
      type: 'resource',
      label: 'RES',
      desc:
          'A rare immortalized bloom carrying ancient regenerative resonance. Its internal structure appears untouched by time, making it highly valuable for advanced restoration research.',
      stock: 28,
      price: 188,
      emoji: '🌸',
      imagePath: 'assets/images/res_29_flower_of_eternity.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 70,
      name: 'Shattered Blade',
      type: 'resource',
      label: 'RES',
      desc:
          'A fractured combat relic recovered from catastrophic interstellar conflicts. Despite its damaged condition, residual offensive resonance still remains dangerously potent.',
      stock: 72,
      price: 92,
      emoji: '⚔️',
      imagePath: 'assets/images/res_30_shattered_blade.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 71,
      name: 'Lost Crystal Data',
      type: 'resource',
      label: 'RES',
      desc:
          'A corrupted crystalline storage fragment containing partially recoverable simulation records. Frequently sought after by hackers and intelligence specialists.',
      stock: 58,
      price: 126,
      emoji: '💠',
      imagePath: 'assets/images/res_31_lost_crystal_data.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 72,
      name: 'Quantum Core Fragment',
      type: 'resource',
      label: 'RES',
      desc:
          'A fragmented quantum-processing core capable of supporting unstable computational synchronization. Highly compatible with cyberwarfare and digital infiltration systems.',
      stock: 52,
      price: 144,
      emoji: '🧿',
      imagePath: 'assets/images/res_32_quantum_core_fragment.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 73,
      name: 'Interastral Ticket',
      type: 'resource',
      label: 'RES',
      desc:
          'An authenticated transportation permit issued for long-range Astral Express operations. These tickets symbolize freedom of travel across connected worlds.',
      stock: 95,
      price: 110,
      emoji: '🎫',
      imagePath: 'assets/images/res_33_interastral_ticket.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 74,
      name: 'Express Supply Crate',
      type: 'resource',
      label: 'RES',
      desc:
          'A sealed logistics container utilized by Astral Express maintenance crews. The crate contains essential operational supplies for extended interstellar expeditions.',
      stock: 68,
      price: 74,
      emoji: '📦',
      imagePath: 'assets/images/res_34_express_supply_crate.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 75,
      name: 'Mechanical Cube: Sam',
      type: 'resource',
      label: 'RES',
      desc:
          'According to legend, this is the heart of a prominent Intellitron leader, containing the Ultimate Source Code, the essence of all inorganic life. Scholars at the Intelligentsia Guild believe that this code holds the key to unraveling the mysteries of inorganic life.',
      stock: 44,
      price: 164,
      emoji: '🔥',
      imagePath: 'assets/images/res_35_mechanical_cube.png',
      rarity: '4-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 76,
      name: 'Molten Propulsion Unit',
      type: 'resource',
      label: 'RES',
      desc:
          'A damaged propulsion component still radiating extreme thermal energy. The internal combustion systems remain partially operational despite catastrophic structural failure.',
      stock: 38,
      price: 172,
      emoji: '🚀',
      imagePath: 'assets/images/res_36_molten_propulsion_unit.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 77,
      name: 'Trailblaze Timer',
      type: 'resource',
      label: 'RES',
      desc:
          'Trailblaze Timer is an item which allows players to permanently increase their max Technique Points.',
      stock: 26,
      price: 210,
      emoji: '📡',
      imagePath: 'assets/images/res_37_trailblaze_timer.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 78,
      name: 'Memory Imprint Shard',
      type: 'resource',
      label: 'RES',
      desc:
          'A fractured memory-storage crystal capable of preserving residual emotional synchronization patterns. Frequently utilized in experimental simulation research.',
      stock: 54,
      price: 138,
      emoji: '🪞',
      imagePath: 'assets/images/res_38_memory_imprint_shard.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 79,
      name: 'Hacked Aether Drive',
      type: 'resource',
      label: 'RES',
      desc:
          'A modified stellar-energy drive illegally rewritten with unauthorized quantum protocols. The unstable synchronization output makes it highly dangerous but extremely efficient.',
      stock: 34,
      price: 198,
      emoji: '💻',
      imagePath: 'assets/images/res_39_hacked_aether_drive.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
    Item(
      id: 80,
      name: 'Cosmic Resonance Chip',
      type: 'resource',
      label: 'RES',
      desc:
          'A high-capacity resonance processor developed for advanced simulation environments. The chip dramatically improves synchronization speed within quantum combat systems.',
      stock: 48,
      price: 176,
      emoji: '🛰️',
      imagePath: 'assets/images/res_40_cosmic_resonance_chip.png',
      rarity: '5-star',
      category: 'RESOURCE',
      eventTag: null,
    ),
  ];
}
